---
- name: Installing productivity applications
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: "{{ casks_install_dir }}"
  with_items:
    - google-chrome
    - virtualbox
    - microsoft-office
    - firefox
    - google-hangouts
    - google-drive
    - vlc
    - hipchat
    - flowdock
    - unrarx
    - alfred
    - flash-player
    - vmware-fusion
  #For items that require sudo
  sudo: yes
