---
- name: Terminal (.bash_profile) profile
  lineinfile:
    dest: ~/.bash_profile
    line: "{{ item.line }}"
  with_items:
    - { line: 'export JAVA_HOME=$(/usr/libexec/java_home)' }
    - { line: 'export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "' }
    - { line: export CLICOLOR=1 }
    - { line: export LSCOLORS=ExFxBxDxCxegedabagacad }
    - { line: alias ls='ls -GFh' }
    - { line: alias lsd='ls -GFhlart' }
