---
- hosts: all
  tasks:
  #   - name: Install HomeBrew Tap Dependencies
  #     homebrew_tap: tap=caskroom/cask state=present
  #     with_items:
  #       - caskroom/cask/brew-cask

    # - name: Install Dependencies via HomeBrew Cask
    #   homebrew_cask: name={{ item }} state=installed
    #   with_items:
    #     - java7

    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - git
        - curl
        - wget
        - ssh-copy-id
        - vim
        - maven
        - ant
        - tree
        - watch
        - colordiff
        - node
        - packer

    - name: Install Gems
      gem: name={{ item }} state=present
      with_items:
        - sass

    - name: Install homebrew cask packages
      homebrew_cask: name={{ item }} state=installed
      with_items:
        - java7
        - google-chrome
        - google-hangouts
        - atom
        - sublime-text3
        - postgres
        - boot2docker
        - vagrant
        - virtualbox
        - vlc
        - hipchat
        - flowdock
        - sourcetree
        - cyberduck
        - python
        - go
