---
- hosts: all
  tasks:
    - name: Install homebrew tap dependencies
      homebrew_tap: tap=caskroom/cask,caskroom/versions state=present

    - name: Install dependencies via homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - brew-cask

    - name: Install Dependencies via homebrew cask
      homebrew_cask: name={{ item }} state=installed
      with_items:
        - java7

    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present update_homebrew=yes upgrade_all=yes
      with_items:
        - git
        - curl
        - wget
        - ssh-copy-id
        - vim
        - maven
        - ant
        - tree
        - watch
        - colordiff
        - node
        - packer

    - name: Install homebrew cask packages
      homebrew_cask: name={{ item }} state=installed
      with_items:
        - google-chrome
        - google-hangouts
        - atom
        - sublime-text3
        - eclipse-java
        - postgres
        - boot2docker
        - vagrant
        - virtualbox
        - vlc
        - hipchat
        - flowdock
        - sourcetree
        - cyberduck
        - python
        - go

    - name: Install Gems
      gem: name={{ item }} state=present
      with_items:
        - sass

    - name: Install global npm packages
      npm: name={{ item }} global=yes
      with_items:
        - esformatter
        - eslint
        - gulp
        - yo
        - babel
        - vtop
        - node-debug
