---
- name: Installing nodejs
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: "{{ casks_install_dir }}"
  with_items:
    - node
- name: Modifying $PATH
  lineinfile:
    dest: ~/.bash_profile
    line: "{{ item.line }}"
  with_items:
    - { line: 'export PATH=/usr/local/bin:$PATH' }

- name: Installing global npm packages
  npm: name={{ item }} global=yes state=present
  with_items:
    - esformatter
    - eslint
    - gulp
    - yo
    - babel
    - vtop
    - node-debug
    - grunt-cli
    - jspm
    - karma-cli
    - webpack
