---
- name: Installing homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions

- name: Installing homebrew cask
  homebrew: name={{ item }} state=present
  with_items:
    - brew-cask

- name: Installing common dependencies
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java7
    - xquartz
  sudo: yes

- name: Installing common Gems
  gem: name={{ item }} state=present
  with_items:
    - sass
    - scss-lint
    - foreman
  sudo: yes

- name: Clone Git Repo for bash completion tools
  get_url: url=https://raw.github.com/git/git/master/contrib/completion/{{item.file}} dest={{git_tools_install_dir}}/{{item.name}}
  with_items:
  - { file: git-prompt.sh, name: .git-prompt.sh }
  - { file: git-completion.bash, name: .git-completion.bash }
