---
- name: Installing homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/versions

- name: Installing homebrew cask
  homebrew: name={{ item }} state=present
  with_items:
    - brew-cask

- name: Installing common dependencies
  homebrew_cask: name={{ item }} state=present
  with_items:
    - java7
    - xquartz
  sudo: yes

- name: Installing common Gems
  gem: name={{ item }} state=present
  with_items:
    - sass
    - scss-lint
  sudo: yes
