---
- name: Installing developer tools
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: "{{ casks_install_dir }}"
  with_items:
    - atom
    - sublime-text3
    - eclipse-java
    - postgres
    - boot2docker
    - vagrant
    - sourcetree
    - cyberduck
    - python
    - go
    - wireshark
    - mou
    - github
    - iterm2
